### ISSUE TITLE
post-link.sh assumes jupyter_core is in the environment

### ISSUE THREAD

**Issue by parente** [conda-forge/widgetsnbextension-feedstock#44]
Issue:

The post-link script has a dependency on jupyter_core for its `ensure_dir_exists` function but the package itself does not list it as a dependency.

```
04:02:29 LinkError: post-link script failed for package widgetsnbextension-3.3.0-py35_0
04:02:29 running your command again with `-v` will provide additional information
04:02:29 location of failed script: /var/jenkins/workspace/conda-out/1532422886675/_t_env/bin/.widgetsnbextension-post-link.sh
04:02:29 ==> script messages <==
04:02:29 Traceback (most recent call last):
04:02:29   File "/var/jenkins/workspace/conda-out/1532422886675/_t_env/bin/jupyter-nbextension", line 4, in <module>
04:02:29     import notebook.nbextensions
04:02:29   File "/var/jenkins/workspace/conda-out/1532422886675/_t_env/lib/python3.5/site-packages/notebook/__init__.py", line 25, in <module>
04:02:29     from .nbextensions import install_nbextension
04:02:29   File "/var/jenkins/workspace/conda-out/1532422886675/_t_env/lib/python3.5/site-packages/notebook/nbextensions.py", line 27, in <module>
04:02:29     from jupyter_core.utils import ensure_dir_exists
04:02:29 ImportError: cannot import name 'ensure_dir_exists'
```

(This was the failure I was looking to catch with #40)

Solutions:

* Switch to using config.d as discussed in #40
* Add jupyter_core as a package dependency

**Comment by jasongrout** [comment]
Looks like jupyter_core already is a dependency of the notebook: https://github.com/conda-forge/notebook-feedstock/blob/4e0308821e2624f080820cd75d1a2666060405cb/recipe/meta.yaml#L31

What version of conda are you using? Is it an older version that had an issue with uninstalling dependencies in the wrong order (IIRC)?

**Comment by parente** [comment]
@jasongrout Good call about notebook. I wasn't paying attention to the trace paths.

I believe this is on conda 4.3 which I thought had the ordering fix, but perhaps not. I'll go recheck.

**Comment by parente** [comment]
Just reproduced with conda 4.5, but the issue appears to be that the offending environment had some package pinning notebook 5.3.x and pulling in jupyter_core 4.3.0. Removing that pin pulls notebook 5.6 and core 4.4.0, and things work as expected. I guess we had an pseudo-API change somewhere down the line in jupyter_core. 

Easy enough for me to workaround here. Sorry for the noise.
